branches:
  only:
  - master
  - stable

language: python

install:
# Install dependency packages
 - pip install boto3
 - pip install requests

before_script: 
 - tree

script:
 - python aws/lambda/pull/main.py

after_script:
 - tree